####################################################################################
# Script: txt_to_csv.3.R
# Author: Wenting Lyu
# Notes: this script helps convert the txt file to cxv file for later analysis.
#         please note that there are two ways to run the script.
#         1) interactive way. 
#         First, run script in console by typing: source("txt_to_csv.3.R") 
#         Second, select the txt file generated by lipidSearch from the poping window
#         Third
#         2) straight way.
#         First comment the interactive way by selecting the interactive block in the code 
#               (comment shortcut: command+shift+c)
#         Second run the code line by line or as a whole
#####################################################################################
rm(list=ls())

list.of.packages <- c("tidyverse", "readr", "magrittr")
need.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[, "Package"])]
if(length(need.packages)) {
  install.packages(need.packages)
}

# path for storing converted files
dir <- "converted"
if(!file.exists(dir)){
  dir.create(dir)
} 

# Suppress the package messages
lapply(list.of.packages, function(x) 
  suppressMessages(require(x, character.only = TRUE, quietly = TRUE)))

files <- read_table(file.choose(), skip_empty_rows = TRUE)
job_name <- names(files) %>% str_split(., "\t") 
file_name <- job_name[[1]][2] %>% paste(., ".csv", sep = "")


index <- sapply(files, function(x) which(str_detect(x, "Rej"))) 
contents <- files %>% filter(row_number() >= index)

# convert data format into data.frame
data <- apply(contents, 1, function(x) str_split(x, "\t") %>% unlist) %>% t() %>% as.data.frame()
colnames(data) <- unlist(data[1, ])
data <- data[-1, ]

sample_neg <- sapply(files, function(x) length(which(str_detect(x, "neg"))))
sample_pos <- sapply(files, function(x) length(which(str_detect(x, "pos"))))

# Verify the sample size info are correct.
message("Reminder: You have ", sample_neg, " samples that were run in negative mode.")
message("Reminder: You have ", sample_pos, " samples that were run in positive mode.")


# reconstruct the data columns and store it into the file
####################################################################################
# selecting the columns we want for analysis
# selecting the columns we want for analysis
selected_cols <- data %>%
  select(contains("ARatio"), contains("APValue"), 
         contains("MainGrade"), contains("MainArea"),
         -contains("NMA"), -contains("Score")
  ) %>% 
  colnames() %>% 
  str_sort(., numeric=TRUE) 

name2 <- paste(dir, "/", file_name, sep = "", collapse = "")

ordered_data <- data %>% 
  select(all_of(selected_cols)) %>% 
  bind_cols(data[, 1:10], .) %>%
  write_csv(., name2)
